# menu_vi_en.yaml

## Where the samples will be written
save_data: /content/drive/MyDrive/qai_hackathon_nmt/run/menu
## Where the vocab(s) will be written
src_vocab: /content/drive/MyDrive/qai_hackathon_nmt/run/menu.vocab.src
tgt_vocab: /content/drive/MyDrive/qai_hackathon_nmt/run/menu.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

Corpus opts:
data:
    corpus_1:
        path_src: /content/drive/MyDrive/qai_hackathon_nmt/data/src-train.txt
        path_tgt: /content/drive/MyDrive/qai_hackathon_nmt/data/tgt-train.txt
    valid:
        path_src: /content/drive/MyDrive/qai_hackathon_nmt/data/src-val.txt
        path_tgt: /content/drive/MyDrive/qai_hackathon_nmt/data/tgt-val.txt      
    test:
        path_src: /content/drive/MyDrive/qai_hackathon_nmt/data/src-test.txt
        path_tgt: /content/drive/MyDrive/qai_hackathon_nmt/data/tgt-test.txt   

# Vocabulary files that were just created
src_vocab: /content/drive/MyDrive/qai_hackathon_nmt/run/menu.vocab.src
tgt_vocab: /content/drive/MyDrive/qai_hackathon_nmt/run/menu.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: /content/drive/MyDrive/qai_hackathon_nmt/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500